sonar.projectKey=pyArchimate_pyArchimate
sonar.organization=pyarchimate
sonar.host.url=https://sonarcloud.io
sonar.python.coverage.reportPaths=build/coverage.xml
sonar.python.version=3.12
sonar.sources=src
sonar.tests=tests
sonar.exclusions=src/pyArchimate/_legacy.py
sonar.test.inclusions=tests/**/*.py
sonar.test.exclusions=tests/legacy_*/**