"""Integration tests for large-model round-trip fidelity.

Tests run against two fixture sets:

1. **Synthetic model** (always available) — generated by
   tests/fixtures/generate_synthetic_model.py with the same element/
   relationship/view proportions as the IT4IT reference architecture.

2. **IT4IT normative fixture** (optional) — copyright The Open Group; not
   redistributable. Obtain ``it4it-normative.xml`` from The Open Group and
   place it at tests/fixtures/it4it-normative.xml.
   The test is skipped automatically when the file is absent.
"""

import tempfile
from pathlib import Path

import pytest

from src.pyArchimate.model import Model
from src.pyArchimate.writers.archimateWriter import archimate_writer
from src.pyArchimate.writers.archiWriter import archi_writer

FIXTURES = Path(__file__).parent.parent / "fixtures"

# Synthetic fixtures — always present, generated from generate_synthetic_model.py
SYNTH_XML = FIXTURES / "synthetic_large.xml"
SYNTH_ARCHIMATE = FIXTURES / "synthetic_large.archimate"

# IT4IT normative fixture — optional, copyright The Open Group
IT4IT_NORMATIVE_XML = FIXTURES / "it4it-normative.xml"

requires_it4it_normative = pytest.mark.skipif(
    not IT4IT_NORMATIVE_XML.exists(), reason="IT4IT normative XML fixture not present (copyright The Open Group)"
)


def _counts(m: Model) -> dict:
    return {
        "elements": len(m.elems_dict),
        "relations": len(m.rels_dict),
        "views": len(m.views_dict),
        "nodes": len(m.nodes_dict),
        "conns": len(m.conns_dict),
    }


class TestSyntheticLargeModel:
    """Round-trip tests using the synthetic large model (always available)."""

    def test_load_synthetic_xml(self):
        """Synthetic XML loads without errors."""
        m = Model()
        m.read(str(SYNTH_XML))
        assert len(m.elems_dict) > 1000
        assert len(m.rels_dict) > 2000
        assert len(m.views_dict) > 100

    def test_load_synthetic_archimate(self):
        """Synthetic .archimate loads without errors."""
        m = Model()
        m.read(str(SYNTH_ARCHIMATE))
        assert len(m.elems_dict) > 1000
        assert len(m.rels_dict) > 2000
        assert len(m.views_dict) > 100

    def test_no_validation_errors_synthetic_xml(self):
        """Synthetic XML model has no orphan nodes or invalid connections."""
        m = Model()
        m.read(str(SYNTH_XML))
        assert m.check_invalid_conn() == []
        assert m.check_invalid_nodes() == []

    def test_no_validation_errors_synthetic_archimate(self):
        """Synthetic .archimate model has no orphan nodes or invalid connections."""
        m = Model()
        m.read(str(SYNTH_ARCHIMATE))
        assert m.check_invalid_conn() == []
        assert m.check_invalid_nodes() == []

    def test_roundtrip_synthetic_xml_preserves_counts(self):
        """Synthetic XML: read→write→read preserves element/relation/view counts."""
        m1 = Model()
        m1.read(str(SYNTH_XML))
        c1 = _counts(m1)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            tmp = f.name
        try:
            m1.write(tmp, writer=archimate_writer)
            m2 = Model()
            m2.read(tmp)
            c2 = _counts(m2)
        finally:
            Path(tmp).unlink(missing_ok=True)

        assert c2["elements"] == c1["elements"]
        assert c2["relations"] == c1["relations"]
        assert c2["views"] == c1["views"]

    def test_roundtrip_synthetic_archimate_preserves_counts(self):
        """Synthetic .archimate: read→write→read preserves all counts."""
        m1 = Model()
        m1.read(str(SYNTH_ARCHIMATE))
        c1 = _counts(m1)

        with tempfile.NamedTemporaryFile(suffix=".archimate", delete=False) as f:
            tmp = f.name
        try:
            m1.write(tmp, writer=archi_writer)
            m2 = Model()
            m2.read(tmp)
            c2 = _counts(m2)
        finally:
            Path(tmp).unlink(missing_ok=True)

        assert c2["elements"] == c1["elements"]
        assert c2["relations"] == c1["relations"]
        assert c2["views"] == c1["views"]
        assert c2["nodes"] == c1["nodes"]
        assert c2["conns"] == c1["conns"]

    def test_roundtrip_synthetic_xml_no_validation_errors(self):
        """Round-tripped synthetic XML has no validation errors."""
        m1 = Model()
        m1.read(str(SYNTH_XML))

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            tmp = f.name
        try:
            m1.write(tmp, writer=archimate_writer)
            m2 = Model()
            m2.read(tmp)
        finally:
            Path(tmp).unlink(missing_ok=True)

        assert m2.check_invalid_conn() == []
        assert m2.check_invalid_nodes() == []


class TestIT4ITLoad:
    """Verify the IT4IT normative XML file loads cleanly without errors."""

    @requires_it4it_normative
    def test_load_it4it_normative_xml(self):
        """IT4IT normative XML loads without errors."""
        m = Model()
        m.read(str(IT4IT_NORMATIVE_XML))
        assert len(m.elems_dict) > 0
        assert len(m.rels_dict) > 0
        assert len(m.views_dict) > 0
