@startuml
title pyArchimate Composite Diagram

object Model {
  - elems_dict : dict[id, Element]
  - rels_dict : dict[id, Relationship]
  - views_dict : dict[id, View]
  - profiles_dict : dict[id, Profile]
  - nodes_dict : dict[id, Node] {registry}
  - conns_dict : dict[id, Connection] {registry}
}

object Element {
  - properties : dict
}

object Relationship {
  - source : Element|Relationship
  - target : Element|Relationship
}

object Profile {
  - concept : str
}

object View {
  - nodes_dict : dict[id, Node]
  - conns_dict : dict[id, Connection]
}

object Node {
  - ref : id {Element|View}
  - parent : View | Node
  - nodes_dict : dict[id, Node] {children}
}

object Connection {
  - ref : id {Relationship}
  - source : Node
  - target : Node
  - bendpoints : list[Point]
}

object Point {
  - x, y : int
}

Model *-- Element
Model *-- Relationship
Model *-- View
Model *-- Profile

View *-- Node
View *-- Connection

Node --> Element : visualizes
Node *-- Node : nested children

Connection --> Relationship : visualizes
Connection o-- Node : source / target
Connection *-- Point : bendpoints

@enduml
